console.log(true && true);
console.log(true && false);
console.log(false || false);
console.log(!false);
console.log("\n");
console.log(5 > 3 && 3 == 2);
console.log(5 > 3 || 3 == 1);
console.log("\n");
console.log(3 == 3 && "Luciano" == "Luciano");
console.log("Rafael" == "Maria" || false);
console.log("\n");
console.log(!(true && true));
console.log(!(!(true && true)));
console.log("\n");
console.log(true && true);
console.log(false || false);